In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import os
import sys

In [2]:
import scanpy as sc
# import scvelo as scv

# read the full GSE dataset
adata = sc.read_h5ad('/Users/evanli/Documents/Research_datasets/Stuart_GSE128639/Stuart_bm_v2.h5ad')
adata.shape

(30011, 17009)

In [3]:
adata.obs.head()

,celltype.l1,celltype.l2,nCount_RNA,nFeature_RNA,nCount_ADT,nFeature_ADT,lane,donor,RNA.weight
a_AAACCTGAGCTTATCG.1,Progenitor_cells,Prog_RBC,7546,2136,1350,25,HumanHTO4,batch1,0.487299
a_AAACCTGAGGTGGGTT.1,T_cell,gdT,1029,437,2970,25,HumanHTO1,batch1,0.245543
a_AAACCTGAGTACATGA.1,T_cell,CD4_Naive,1111,429,2474,23,HumanHTO5,batch1,0.501680
a_AAACCTGCAAACCTAC.1,T_cell,CD4_Memory,2741,851,4799,25,HumanHTO3,batch1,0.431308
a_AAACCTGCAAGGTGTG.1,Mono&DC,CD14_Mono,2099,843,5434,25,HumanHTO2,batch1,0.572097

In [9]:
# Create a new column 'celltype.l2.merge' that is a copy of 'celltype.l2'
adata.obs['celltype.l2.merge'] = adata.obs['celltype.l2']

# Replace 'CD8_Effector_1' and 'CD8_Effector_2' with 'CD8_Effector' in the new column
adata.obs['celltype.l2.merge'].replace(['CD8_Effector_1', 'CD8_Effector_2'], 'CD8_Effector', inplace=True)
adata.obs['celltype.l2.merge'].replace(['CD8_Memory_1', 'CD8_Memory_2'], 'CD8_Memory', inplace=True)
adata.obs['celltype.l2.merge'].replace(['Prog_B_1', 'Prog_B_2'], 'Prog_B', inplace=True)
adata.obs['celltype.l2.merge'].value_counts()

CD14_Mono         6435
CD4_Naive         4370
CD8_Naive         3835
CD4_Memory        3329
Naive_B           1892
Memory_B          1620
NK                1251
CD8_Memory         987
CD8_Effector       874
Prog_RBC           745
GMP                739
MAIT               514
cDC2               474
CD16_Mono          427
gdT                366
pDC                322
Treg               291
LMPP               287
Prog_B             268
Prog_DC            260
HSC                258
Plasmablast        221
CD56_bright_NK     125
Prog_Mk            121
Name: celltype.l2.merge, dtype: int64

In [11]:
adata.obs.head()

,celltype.l1,celltype.l2,nCount_RNA,nFeature_RNA,nCount_ADT,nFeature_ADT,lane,donor,RNA.weight,celltype.l2.merge
a_AAACCTGAGCTTATCG.1,Progenitor_cells,Prog_RBC,7546,2136,1350,25,HumanHTO4,batch1,0.487299,Prog_RBC
a_AAACCTGAGGTGGGTT.1,T_cell,gdT,1029,437,2970,25,HumanHTO1,batch1,0.245543,gdT
a_AAACCTGAGTACATGA.1,T_cell,CD4_Naive,1111,429,2474,23,HumanHTO5,batch1,0.501680,CD4_Naive
a_AAACCTGCAAACCTAC.1,T_cell,CD4_Memory,2741,851,4799,25,HumanHTO3,batch1,0.431308,CD4_Memory
a_AAACCTGCAAGGTGTG.1,Mono&DC,CD14_Mono,2099,843,5434,25,HumanHTO2,batch1,0.572097,CD14_Mono